### ISSUE TITLE
KMP JS-only module Exception

### ISSUE THREAD

**Issue by AlecStrong** [vanniktech/gradle-maven-publish-plugin#141]
Stack trace:

```
Caused by: org.gradle.api.UnknownDomainObjectException: SoftwareComponentInternal with name 'java' not found.
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:503)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:332)
	at com.vanniktech.maven.publish.MavenPublishConfigurer.configureJavaArtifacts(MavenPublishConfigurer.kt:195)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin.configurePublishing(BaseMavenPublishPlugin.kt:97)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin.access$configurePublishing(BaseMavenPublishPlugin.kt:15)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin$apply$1.execute(BaseMavenPublishPlugin.kt:46)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin$apply$1.execute(BaseMavenPublishPlugin.kt:15)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.lambda$run$0(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:92)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy38.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:191)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:188)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1434)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:197)
	... 115 more
```

happens in a kotlin multiplatform module with only js configured.

Searching the repo looks like `BaseMavenPublishPlugin` has disappeared, has this been fixed on master?

**Comment by vanniktech** [comment]
Correct me wrong @gabrielittner, but this was part of the legacy infrastructure which we've deleted.

**Comment by gabrielittner** [comment]
This would still be an issue. Which plugins do you have applied exactly?

**Comment by AlecStrong** [comment]
https://github.com/cashapp/sqldelight/blob/master/drivers/sqljs-driver/build.gradle

**Comment by gabrielittner** [comment]
#142 will fix the failing build, but will not make `org.jetbrains.kotlin.js` publishable.

**Comment by AlecStrong** [comment]
interesting, i think it would be to have it published like a multiplatform target, in which case your suggestion of making it a mpp module would probably work.

**Comment by gabrielittner** [comment]
I'm closing this one then
