### ISSUE TITLE
Question: Can I specify whether to include sources and javadocs?

### ISSUE THREAD

**Issue by makethemo** [vanniktech/gradle-maven-publish-plugin#164]
Hello,
I've used the 0.13.0 version of the library and I am satisfied that it can be easily applied :)
By the way, I've confirmed that it uploads sources and javadocs together.
Is there any configuration to exclude them?

**Comment by gabrielittner** [comment]
There is no direct way right now, #138 will make this easier.

You could try adding this snippet to the end of your build script, that should remove the 2 artifacts:
```
afterEvaluate {
  configure<PublishingExtension> {
    publications.withType<MavenPublication>().configureEach {
        setArtifacts(artifacts.matching { it.classifier != "javadoc" && it.classifier != "sources" })
    }
  }
}
```

**Comment by makethemo** [comment]
Thank you for answer.

```
Cause: startup failed:
script '.../maven-publish.gradle': 23: unexpected token: > @ line 23, column 34.
       configure<PublishingExtension> {
                                    ^

1 error
```
```
Cause: startup failed:
script '.../maven-publish.gradle': 24: unexpected token: > @ line 24, column 47.
   ions.withType<MavenPublication>().config
                                 ^

1 error
```

<br>

The snippet you shared did not work in my Android project, so I modified some.

```groovy
afterEvaluate {
    publishing {
        publications {
            withType(MavenPublication).configureEach {
                setArtifacts(artifacts.matching { it.classifier != "javadoc" && it.classifier != "sources" })
            }
        }
    }
}
```

<br>

But it still didn't work.
It seems that the artifacts that have already been set cannot be modified.
Are there any other alternatives that I can try at this point?

https://github.com/gradle/gradle/blob/d3d731e39d2c905ddf54d2077ebdd90146a011c2/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L792-L812

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-module:generateMetadataFileForMavenPublication'.
> Cannot publish module metadata where component artifacts are modified.

...
Caused by: org.gradle.api.artifacts.PublishException: Cannot publish module metadata where component artifacts are modified.
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.checkThatArtifactIsPublishedUnmodified(DefaultMavenPublication.java:755)
        at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.getPublishedFile(DefaultMavenPublication.java:712)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.writeArtifact(GradleModuleMetadataWriter.java:382)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.writeArtifacts(GradleModuleMetadataWriter.java:376)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.writeVariantHostedInThisModule(GradleModuleMetadataWriter.java:328)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.writeVariants(GradleModuleMetadataWriter.java:230)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.writeComponentWithVariants(GradleModuleMetadataWriter.java:144)
        at org.gradle.api.publish.internal.GradleModuleMetadataWriter.generateTo(GradleModuleMetadataWriter.java:112)
...
```

**Comment by gabrielittner** [comment]
Something else you could try is removing/overriding the inputs of the javadoc and sources jar tasks. So that it would just produce empty jars.

**Comment by gabrielittner** [comment]
I don't think we will offer an option for this on the main plugin, however in 0.15.0 we have an (experimental) base plugin which allows you to configure everything on your own, including sources and javadocs. https://github.com/vanniktech/gradle-maven-publish-plugin#base-plugin

**Comment by 4face-studi0** [comment]
I'm facing the same mentioned exception 
> Execution failed for task ':my-module:generateMetadataFileForKotlinMultiplatformPublication'.
> Cannot publish module metadata where component artifacts are modified.

And I really don't know why? I didn't try anything exotic
