### ISSUE TITLE
Plugin still attempts to make `uploadArchives` depend on maven central publish task even if central is disabled

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#274]
```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'publishAllPublicationsToMavenCentralRepository' not found in project ':slack-plugin'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:360)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:112)
        at com.vanniktech.maven.publish.legacy.TasksKt$configureArchivesTasks$1.execute(Tasks.kt:8)
        at com.vanniktech.maven.publish.legacy.TasksKt$configureArchivesTasks$1.execute(Tasks.kt)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
```

**Comment by vRallev** [comment]
Very easy to reproduce `./gradlew :your:module:tasks` after setting 
```
mavenPublish {
  sonatypeHost = null
}
```

**Comment by gabrielittner** [comment]
I think I will do a quick 0.17.0 this week and just remove uploadArchives. It's been deprecated for a while now

**Comment by ZacSweers** [comment]
Put up a PR here https://github.com/vanniktech/gradle-maven-publish-plugin/pull/276

**Comment by gabrielittner** [comment]
0.17.0 where uploadArchives got removed is out.
