### ISSUE TITLE
Incompatible with 1.0.0 of Gradle's `com.gradle.plugin-publish`plugin?

### ISSUE THREAD

**Issue by benjamin-bader** [vanniktech/gradle-maven-publish-plugin#387]
Use of `com.gradle.plugin-publish` is required to publish plugins to Gradle's plugin repository.  As of the recently-released version  1.0.0, it seems that `gradle-maven-publish-plugin` is incompatible with Gradle's own plugin:

```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'dexcount-gradle-plugin'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
	...
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'signDexcountPluginMarkerMavenPublication' as a task with that name already exists.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:257)
	...
	at org.gradle.plugins.signing.SigningExtension.sign(SigningExtension.java:395)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.signAllPublications(MavenPublishBaseExtension.kt:114)
	at com.vanniktech.maven.publish.MavenPublishPlugin.apply$lambda-0(MavenPublishPlugin.kt:65)
        ...
```

Interestingly, swapping the order of plugins in the `plugins` block so that this plugin comes before Gradle's, works around the issue.  Would it be possible for this plugin to adapt to the presence of the Gradle plugin?  Or should I be filing an issue with them instead?

**Comment by gabrielittner** [comment]
If it's working when swapping the order than there should be something we can do about it, I'll take a look.

**Comment by gabrielittner** [comment]
This is what the publish plugin does to setup signing:
```
private void wireInSigningTask(Project project, SigningExtension signing, Publication publication) {
    String signTaskName = determineSignTaskNameForPublication(publication);
    Task signTask = project.getTasks().findByName(signTaskName);
    if (signTask == null) {
        signTask = signing.sign(publication).get(0);
    }
    dependsOn(signTask);
}
```

We can add the same conditional to check if the task already exists. Generally though it feels a bit weird

**Comment by gabrielittner** [comment]
Filed https://github.com/gradle/gradle/issues/21857

**Comment by gabrielittner** [comment]
I've added the workaround from the plugin-publish plugin until it is fixed on Gradle's side, will be in the next release
