### ISSUE TITLE
How to set a custom host in publishToMavenCentral?

### ISSUE THREAD

**Issue by yschimke** [vanniktech/gradle-maven-publish-plugin#503]
```
fun publishToMavenCentral(host: SonatypeHost = SonatypeHost.DEFAULT, automaticRelease: Boolean = false) {
```

SonatypeHost is an enum, so how to set a custom host in the form of xxx.oss.sonatype.org for publishing to Sonetype?

DEFAULT and use SONATYPE_HOST env? Can the enum be opened up to a value type?

**Comment by yschimke** [comment]
That doesn't work.

```
Caused by: java.lang.IllegalArgumentException: No enum constant com.vanniktech.maven.publish.SonatypeHost.google.oss.sonatype.org
        at com.vanniktech.maven.publish.SonatypeHost.valueOf(SonatypeHost.kt)
        at com.vanniktech.maven.publish.MavenPublishPlugin.apply(MavenPublishPlugin.kt:20)
        at com.vanniktech.maven.publish.MavenPublishPlugin.apply(MavenPublishPlugin.kt:11)
```
