### ISSUE TITLE
Gradle build issue

### ISSUE THREAD

**Issue by robertlevonyan** [vanniktech/gradle-maven-publish-plugin#522]
Gradle build fails with this error 

```
* Exception is:
java.lang.IllegalStateException: The value for this property is final and cannot be changed any further.
	at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:498)
	at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:272)
	at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:221)
	at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.publishToMavenCentral(MavenPublishBaseExtension.kt:53)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.publishToMavenCentral$default(MavenPublishBaseExtension.kt:52)
```

The error line is on this line:
```  
publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.S01)
```

**Comment by jumaallan** [comment]
This is the config inside `gradle.properties` (global one)
```
mavenCentralUsername=
mavenCentralPassword=

signing.keyId=
signing.password=
signing.secretKeyRingFile=/Users/jumaallan/secring.gpg

SONATYPE_HOST=S01
RELEASE_SIGNING_ENABLED=true
```

Added this inside the library `build.gradle.kts`

```
mavenPublishing {

    // publish to https://s01.oss.sonatype.org
    publishToMavenCentral(SonatypeHost.S01, true)

    signAllPublications()
}
```

Using `AGP 7.5`

@gabrielittner

**Comment by jumaallan** [comment]
The plugin is also applied on the module

**Comment by gabrielittner** [comment]
The error happens because you are adding the property and calling the method for the same thing.

```
SONATYPE_HOST=S01
RELEASE_SIGNING_ENABLED=true
```
and 
```
publishToMavenCentral(SonatypeHost.S01, true)
```
do the same thing. It should work if you remove either the 2 properties or the method call

**Comment by jumaallan** [comment]
> ing. It should work if you re

Thank you

Worked 😄

**Comment by jumaallan** [comment]
> The error happens because you are adding the property and calling the method for the same thing.
> 
> ```
> SONATYPE_HOST=S01
> RELEASE_SIGNING_ENABLED=true
> ```
> 
> and
> 
> ```
> publishToMavenCentral(SonatypeHost.S01, true)
> ```
> 
> do the same thing. It should work if you remove either the 2 properties or the method call

Thank you

Worked 😄
