### ISSUE TITLE
Missing parameters should trigger more explicit errors

### ISSUE THREAD

**Issue by martinbonnin** [vanniktech/gradle-maven-publish-plugin#61]
Omitting `GROUP` from `gradle.properties` triggers `groupId is required to be set`

Omitting `POM_ARTIFACT_ID` triggers a NullPointerException:

    Caused by: java.lang.NullPointerException
            at org.gradle.api.publication.maven.internal.DefaultArtifactPom.assignArtifactValuesToPom(DefaultArtifactPom.java:105)
            at org.gradle.api.publication.maven.internal.DefaultArtifactPom.addArtifact(DefaultArtifactPom.java:89)
            at org.gradle.api.publication.maven.internal.DefaultArtifactPomContainer.addArtifact(DefaultArtifactPomContainer.java:52)
            at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.collectArtifact(AbstractMavenResolver.java:103)
            at org.gradle.api.publication.maven.internal.deployer.AbstractMavenResolver.publish(AbstractMavenResolver.java:94)
            at org.gradle.api.publication.maven.internal.deployer.BaseMavenDeployer.publish(BaseMavenDeployer.java:34)
            at org.gradle.api.internal.artifacts.ivyservice.publisher.DefaultIvyDependencyPublisher.publish(DefaultIvyDependencyPublisher.java:42)
            at org.gradle.api.internal.artifacts.ivyservice.publisher.IvyBackedArtifactPublisher.publish(IvyBackedArtifactPublisher.java:78)
            at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher$1.execute(IvyContextualArtifactPublisher.java:43)
            at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher$1.execute(IvyContextualArtifactPublisher.java:40)
            at org.gradle.internal.Transformers$4.transform(Transformers.java:133)
            at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
            at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
            at org.gradle.api.internal.artifacts.ivyservice.IvyContextualArtifactPublisher.publish(IvyContextualArtifactPublisher.java:40)
            at org.gradle.api.tasks.Upload.upload(Upload.java:65)

It would be nice for onboarding if these errors could be made more explicit (Something like "Please define GROUP/POM_ARTIFACT_ID/... in your gradle.properties")

**Comment by vanniktech** [comment]
Yes. Can do. Want to submit a PR?

**Comment by martinbonnin** [comment]
Yep, I can look into this.

**Comment by wesleyk** [comment]
Just ran into this issue. Thanks for the fix! @vanniktech any sense of when this will get released in a new version of the plugin?

Thanks!

**Comment by vanniktech** [comment]
#54 needs to be fixed first
