### ISSUE TITLE
Attempting to configure publishing platform object results in build failure

### ISSUE THREAD

**Issue by mattinger** [vanniktech/gradle-maven-publish-plugin#624]
I am attempting to use the plugin to configure an android library that has a single product dimension.  however, when i try to configure the platform in the mavenPublish block, i always get a failure. I've simplified this down to a project that doesn't even have any dimensions to it.  I consistently get this error:

```
Cause 1: java.lang.IllegalStateException: The value for this property is final and cannot be changed any further.
	at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:498)
	at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:272)
	at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:221)
	at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.configure(MavenPublishBaseExtension.kt:346)
	at com.vanniktech.maven.publish.MavenPublishPluginKt$configurePlatform$2$1.invoke(MavenPublishPlugin.kt:45)
	at com.vanniktech.maven.publish.MavenPublishPluginKt$configurePlatform$2$1.invoke(MavenPublishPlugin.kt:42)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$finalizeDsl$1.execute(AndroidComponentsExtensionImpl.kt:47)
	at com.android.build.api.extension.impl.AndroidComponentsExtensionImpl$finalizeDsl$1.execute(AndroidComponentsExtensionImpl.kt:46)
```

I debugged through this a bit and i found that while it is setting the value i've put in the mavenPublishing block, the plugin itself is trying to do some finalization related to creating the gradle tasks, which is forcible setting the value again.  But since that value has been finalized, it can't do that.  In addition, it's also making an assumption about the platform type when it does this, attempting to set it back to AndroidSingleVariantLibrary.

```
  plugins.withId("com.android.library") {
    // afterEvaluate is too late, but we can't run this synchronously because we shouldn't call the APIs for
    // multiplatform projects that use Android
    androidComponents.finalizeDsl {
      if (!plugins.hasPlugin("org.jetbrains.kotlin.multiplatform")) {
        val variant = project.findOptionalProperty("ANDROID_VARIANT_TO_PUBLISH") ?: "release"
        baseExtension.configure(AndroidSingleVariantLibrary(variant))
      }
    }
  }

```

Below are the contents of my gradle files, which is all you need to produce this issue using gradle 8.2.1

build.gradle.kts

```
import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

plugins {
    id("com.android.library") version("8.1.0")
    id("org.jetbrains.kotlin.android") version("1.8.21")
    id("com.vanniktech.maven.publish") version("0.25.3")
}

android {
    namespace = "com.maven.publish.bug"
    defaultConfig {
        compileSdk = 33
    }

    buildTypes {
        getByName("debug") {

        }

        getByName("release") {

        }
    }
}

mavenPublishing {
    configure(
        AndroidSingleVariantLibrary(
            sourcesJar = true,
            publishJavadocJar = true,
            variant = "release"
        )
    )
}
```

settings.gradle.kts
```
rootProject.name = "maven-publish-bug"

pluginManagement {
    repositories {
        mavenCentral()
        google()
    }
}
```

**Comment by gabrielittner** [comment]
This will properly work without having to use base plugin in the next release
