### ISSUE TITLE
Using `mavenPublishing { coordinates(groupId) }` crashes complaining that groupId is already set

### ISSUE THREAD

**Issue by StylianosGakis** [vanniktech/gradle-maven-publish-plugin#661]
In my build.gradle.kts file I got some code:
```
val authlibGroupId = ...
val authlibVersion = ...
version = authlibVersion
group = authlibGroupId

mavenPublishing {
    coordinates(
        groupId = authlibGroupId,
        artifactId = "authlib",
        version = authlibVersion,
    )
    ...
```
But this combination seems to crash, since it tries to set the version + groupId

The stacktrace starts like this:
```
Exception is:
java.lang.IllegalStateException: The value for extension 'mavenPublishing' property 'groupId$plugin' is final and cannot be changed any further.
	at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:498)
	at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:272)
	at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:221)
	at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.groupId(MavenPublishBaseExtension.kt:173)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.coordinates(MavenPublishBaseExtension.kt:167)
```
Which means that it's trying to run this line https://github.com/vanniktech/gradle-maven-publish-plugin/blob/cfd2a0d6a37304cfd90b2631d188e76dd0dccbae/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L173 and it fails since I suppose it already picks up the value from me setting it earlier.
But without running `coordinates` I do not see a way to set the `artifactId`, if the `version` and `groupId` are picked up automatically.

Am I approaching this completely wrong for some reason, or is there something I should be doing here instead?

**Comment by StylianosGakis** [comment]
Nah nvm, seems like it was not picked up from the lines above, but from `gradle.properties` having `GROUP=com....` and it was auto-loading it from there instead.
Rubber ducked myself a bit here 🙈
