### ISSUE TITLE
Getting "The value for this property is final and cannot be changed any further"

### ISSUE THREAD

**Issue by sschuberth** [vanniktech/gradle-maven-publish-plugin#675]
I was trying to configure the plugin with [Dokkatoo](https://github.com/adamko-dev/dokkatoo), an alternative to Dokka, like this:

    configure(KotlinJvm(JavadocJar.Dokka("dokkatooGeneratePublicationJavadoc")))

which gives

```
Caused by: java.lang.IllegalStateException: The value for this property is final and cannot be changed any further.
        at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:498)
        at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:272)
        at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:221)
        at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
        at com.vanniktech.maven.publish.MavenPublishBaseExtension.configure(MavenPublishBaseExtension.kt:346)
        at com.vanniktech.maven.publish.MavenPublishPluginKt$configurePlatform$3.invoke(MavenPublishPlugin.kt:59)
        at com.vanniktech.maven.publish.MavenPublishPluginKt$configurePlatform$3.invoke(MavenPublishPlugin.kt:50)
        at com.vanniktech.maven.publish.MavenPublishPluginKt.configurePlatform$lambda$2(MavenPublishPlugin.kt:50)
```

For the record, I'm getting the same when using "dokkaHtml" instead of "dokkatooGeneratePublicationJavadoc".

I'm using Gradle 8.5.

**Comment by gabrielittner** [comment]
`configure` currently can only be called from the [base plugin](https://vanniktech.github.io/gradle-maven-publish-plugin/base/). I need to take another look at that, the reason in the past was that because of how some other plugins behave we can't wait with calling it for the automatic project type detection that the main plugin does. If that's still the case I'll at least add a better error message.

**Comment by gabrielittner** [comment]
This will properly work without having to use base plugin in the next release

**Comment by gdude2002** [comment]
Running into this again in 0.30.0, when attempting to configure via a buildSrc convention plugin:

```kt
mavenPublishing {
	if (isSnapshot) {
		publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)
	}

	configure(KotlinJvm(
		javadocJar = JavadocJar.Dokka("dokkaGeneratePublicationHtml"),
		sourcesJar = true
	))

	signAllPublications()

	coordinates(project.group.toString(), project.name, project.version.toString())

	pom {
		// ...
	}
}
```
