### ISSUE TITLE
"Remove shutdown hook failed" when using with dokkatoo task

### ISSUE THREAD

**Issue by sschuberth** [vanniktech/gradle-maven-publish-plugin#688]
This is a follow-up to https://github.com/vanniktech/gradle-maven-publish-plugin/issues/675 in the sense that I'm still trying to get this plugin to work with *dokkatoo* creating the doc JARs.

This time

    configure(KotlinJvm(JavadocJar.Dokka("dokkatooGeneratePublicationJavadoc")))

results in

```
> Task :plugins:commands:downloader-command:dokkatooGeneratePublicationJavadoc FAILED
Remove shutdown hook failed
java.lang.IllegalStateException: Shutdown in progress
        at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:245)
        at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:38)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:208)
        at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:382)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:132)
        at org.gradle.process.internal.ExecHandleRunner.lambda$run$2(ExecHandleRunner.java:97)
        at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:95)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Any clue what's going on?

This can be reproduced with https://github.com/oss-review-toolkit/ort/tree/gradle-maven-publish-plugin and running

    ./gradlew -Pversion=1.0.0 publishToMavenLocal

**Comment by sschuberth** [comment]
> This can be reproduced

Hmm, actually another run just succeeded...

**Comment by sschuberth** [comment]
Ok, thanks for checking. So let me close this and eventually reopen when I can reproduce it.
