### ISSUE TITLE
Unable to read secret key

### ISSUE THREAD

**Issue by iRedTea** [vanniktech/gradle-maven-publish-plugin#800]
I try to run signMavenPublication, but it throws an error:
> Unable to read secret key from file: D:\IdeaProjects\KotlinBukkitKit\secret\file.txt (it may not be a PGP secret key ring)

Steps for getting error:
1) create new key using gpg --full-generate-key
2) get file with private key using `gpg --export-secret-keys --armor 768C45A881BB7C2F7A1AE5331E8615603B8C26C1 | grep -v '\-\-' | grep -v '^=.' | tr -d '\n' &> file.txt`
3) set this properties to gradle.properties:
signing.keyId=768C45A881BB7C2F7A1AE5331E8615603B8C26C1
signing.password=**_hidden_**
signing.secretKeyRingFile=../secret/file.txt

**Comment by iRedTea** [comment]
Stacktrace:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':architecture:signMavenPublication'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.api.InvalidUserDataException: Unable to read secret key from file: D:\IdeaProjects\KotlinBukkitKit\secret\file.txt (it may not be a PGP secret key ring)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.readSecretKey(PgpSignatoryFactory.java:142)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.readSecretKey(PgpSignatoryFactory.java:123)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.createSignatory(PgpSignatoryFactory.java:69)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.readProperties(PgpSignatoryFactory.java:95)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.createSignatory(PgpSignatoryFactory.java:45)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.createSignatory(PgpSignatoryFactory.java:49)
	at org.gradle.security.internal.pgp.BasePgpSignatoryProvider.getDefaultSignatory(BasePgpSignatoryProvider.java:38)
	at org.gradle.security.internal.pgp.BasePgpSignatoryProvider.getDefaultSignatory(BasePgpSignatoryProvider.java:30)
	at org.gradle.plugins.signing.SigningExtension.getSignatory(SigningExtension.java:200)
	at org.gradle.plugins.signing.SigningExtension_Decorated.getSignatory(Unknown Source)
	at org.gradle.util.internal.GUtil.uncheckedCall(GUtil.java:437)
	at org.gradle.internal.extensibility.ConventionAwareHelper$2.doGetValue(ConventionAwareHelper.java:96)
	at org.gradle.internal.extensibility.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:147)
	at org.gradle.internal.extensibility.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:129)
	at org.gradle.plugins.signing.Sign_Decorated.getSignatory(Unknown Source)
	at org.gradle.plugins.signing.Sign.computeCachedSignatures(Sign.java:81)
	at org.gradle.plugins.signing.Sign.sanitizedGenerators(Sign.java:268)
	at org.gradle.plugins.signing.Sign.getGeneratorsByKey(Sign.java:252)
	at org.gradle.plugins.signing.Sign_Decorated.getGeneratorsByKey(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor690.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.annotations.impl.DefaultPropertyAnnotationMetadata.getPropertyValue(DefaultPropertyAnnotationMetadata.java:97)
	at org.gradle.internal.properties.annotations.DefaultTypeMetadataStore$DefaultPropertyMetadata.getPropertyValue(DefaultTypeMetadataStore.java:266)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.getChild(AbstractTypeMetadataWalker.java:221)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.lambda$walkNestedChild$2(AbstractTypeMetadataWalker.java:178)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.walkNestedChild(AbstractTypeMetadataWalker.java:190)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.walkNestedChild(AbstractTypeMetadataWalker.java:177)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker$InstanceTypeMetadataWalker.walkNestedChild(AbstractTypeMetadataWalker.java:123)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.lambda$walkChildren$4(AbstractTypeMetadataWalker.java:85)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.walkChildren(AbstractTypeMetadataWalker.java:83)
	at org.gradle.internal.properties.annotations.AbstractTypeMetadataWalker.walk(AbstractTypeMetadataWalker.java:53)
	at org.gradle.internal.properties.bean.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:64)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitAnnotatedProperties(TaskPropertyUtils.java:58)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:45)
	at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:75)
	at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:231)
	at org.gradle.execution.plan.ResolveMutationsNode.doResolveMutations(ResolveMutationsNode.java:106)
	at org.gradle.execution.plan.ResolveMutationsNode.access$000(ResolveMutationsNode.java:31)
	at org.gradle.execution.plan.ResolveMutationsNode$1.run(ResolveMutationsNode.java:87)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.execution.plan.ResolveMutationsNode.execute(ResolveMutationsNode.java:83)
	at org.gradle.execution.plan.WorkNodeExecutor.execute(WorkNodeExecutor.java:27)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: java.io.IOException: unknown object in stream: 44
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.bouncycastle.openpgp.bc.BcPGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.gradle.plugins.signing.signatory.pgp.PgpSignatoryFactory.readSecretKey(PgpSignatoryFactory.java:140)
	... 56 more

**Comment by gabrielittner** [comment]
There are 2 options. Either you provide properties that point to a gpg file like this (when doing this you don't need step 2):
```
signing.keyId=12345678
signing.password=secret
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg
```
or you use the in memory key directly (so instead of writing the output of step 2 you directly use the value):
```
signingInMemoryKeyId=12345678
signingInMemoryKeyPassword=secret
signingInMemoryKey=<output of the command>
```
