### ISSUE TITLE
Support Dokka 2

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#854]
Dokka 2 changes around some of the task names

```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'dokkaHtml' not found in project ':tools:cli'.
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:119)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:47)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:385)
        at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:129)
        at com.vanniktech.maven.publish.tasks.JavadocJar$Companion.dokkaJavadocJar$lambda$6$lambda$4(JavadocJar.kt:45)
        at com.vanniktech.maven.publish.tasks.JavadocJar$Companion.dokkaJavadocJar$lambda$6$lambda$5(JavadocJar.kt:45)

```

**Comment by gabrielittner** [comment]
Already merged https://github.com/vanniktech/gradle-maven-publish-plugin/pull/849. I'll cut a release on the weekend at latest
