### ISSUE TITLE
java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by anggrayudi** [vanniktech/gradle-maven-publish-plugin#93]
I've just noticed that version `0.8.0` fails my project's build:
```
Caused by: java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
	at com.vanniktech.maven.publish.MavenPublishPom$Companion.fromProject(MavenPublishPom.kt:32)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin.apply(BaseMavenPublishPlugin.kt:12)
	at com.vanniktech.maven.publish.BaseMavenPublishPlugin.apply(BaseMavenPublishPlugin.kt:7)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:267)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:155)
	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:152)
	... 138 more
```

BTW, I am using Android Studio 3.5.3 with Gradle 5.4.1. Do you have the same error?

**Comment by gabrielittner** [comment]
I haven't seen this before. Are you setting any properties in your build.gradle files?

**Comment by anggrayudi** [comment]
I did. It seems that `findProperty()` returns `org.codehaus.groovy.runtime.GStringImpl`. It is better if we use `toString()` method.

```kotlin
val value = project.findProperty(propertyName)?.toString()
```

**Comment by anggrayudi** [comment]
Hmm... What about this line @gabrielittner ?

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/da4ba309a2969c53979e04cef24debbf903698e8/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPom.kt#L57

**Comment by vanniktech** [comment]
Seems like `findMandatoryProperty` should use `findOptionalProperty`

**Comment by gabrielittner** [comment]
Good catch, I missed that one.

**Comment by gabrielittner** [comment]
https://github.com/vanniktech/gradle-maven-publish-plugin/pull/95

**Comment by anggrayudi** [comment]
Can we have snapshot version now @gabrielittner @vanniktech ? I just want to test it.

**Comment by gabrielittner** [comment]
Snapshot will be published by this CI job https://travis-ci.org/vanniktech/gradle-maven-publish-plugin/builds/642427179

**Comment by anggrayudi** [comment]
Now it works as expected. Thank you @gabrielittner @vanniktech 👍👍
